// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://swtlnfsljzdmnlzpzoux.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3dGxuZnNsanpkbW5senB6b3V4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2OTY2MTksImV4cCI6MjA3MzI3MjYxOX0.8N-rIJQClnESCZyNWFFnuIpBtc7oyfL7WJ8gxjsIW4A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});